version: '2'

services:

    app-autos:

        container_name: 'Angular-App-Autos'

        build:

            context: .

            dockerfile: Dockerfile

        restart: always

        ports:

            - '80'

        environment:

            - VIRTUAL_HOST=app.midominio.com